# Generated by Django 6.0.3 on 2026-04-14 14:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.category', verbose_name='Categoría padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe empezar con +998 y tener 12 dígitos', regex='^\\+998\\d{9}$')], verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment', models.TextField(blank=True, verbose_name='Comentarios')),
                ('items', models.JSONField(verbose_name='Items del pedido')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio total (UZS)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('waiting_for_payment', 'Esperando pago'), ('checking', 'Verificando pago'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Imagen del recibo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='shop_order_status_63c2c0_idx'), models.Index(fields=['created_at'], name='shop_order_created_86b012_idx'), models.Index(fields=['phone'], name='shop_order_phone_6c7e9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio (UZS)')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('specs', models.JSONField(default=dict, verbose_name='Especificaciones')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen del producto')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('condition', models.CharField(choices=[('new', 'Nuevo'), ('used', 'Usado'), ('refurbished', 'Reacondicionado')], default='new', max_length=20, verbose_name='Condición')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'), models.Index(fields=['category'], name='shop_produc_categor_d249e3_idx'), models.Index(fields=['brand'], name='shop_produc_brand_ae7a9e_idx'), models.Index(fields=['price'], name='shop_produc_price_3b79b5_idx'), models.Index(fields=['is_active'], name='shop_produc_is_acti_2257ae_idx')],
            },
        ),
    ]
